### ISSUE TITLE
SAP GUI for Windows: Issues with chromium-based browser control (WebView/Edge)

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#4841]
Collection of issues as discussed in the slack channel and PR  #4840
These errors only occur with SAPGUI 7.70 for windows PL2 and chromium based browser control. None of the occur with IE control or with previous patch level.

- [x] "Unknown action: SELECT" -> #4840
- [x] Back navigation doesn't work -> https://github.com/abapGit/abapGit/pull/4840#issuecomment-860035017
- [ ] Patch doesn't work - add file and click 'Patch'
![image](https://user-images.githubusercontent.com/17437789/121778138-ece61780-cb95-11eb-9af3-a2097200ea6c.png)
- [x] Diff doesn't work -> Shortdump
![image](https://user-images.githubusercontent.com/17437789/121778192-2c146880-cb96-11eb-8b79-69a98ef6d585.png)
![image](https://user-images.githubusercontent.com/17437789/121778195-2fa7ef80-cb96-11eb-9a1c-6624d8358431.png)
Filename is UPPERCASE
![image](https://user-images.githubusercontent.com/17437789/121778196-320a4980-cb96-11eb-8f8f-1c68c8e8a413.png)
![image](https://user-images.githubusercontent.com/17437789/121778200-346ca380-cb96-11eb-95af-c2a6527dbcb4.png)

- [ ] Stage page: 'Change by (me)' doesn't work
![image](https://user-images.githubusercontent.com/17437789/121778392-ff148580-cb96-11eb-88d4-dd884c018fe3.png)
![image](https://user-images.githubusercontent.com/17437789/121778389-fc199500-cb96-11eb-821f-ffba06952d2f.png)

- [x] Bad performance. Every navigation step/action takes ~2 seconds

**Comment by jrodriguez-rc** [comment]
I just test the PL03 and it seems that all the problems (or at least almost) are fixed.

@christianguenter2 can you test it with the last PL03?

**Comment by christianguenter2** [comment]
Thanks for the info. I just did a quick test and some issues are fixed (marked above). Few still exist. 
@jrodriguez-rc Is your OCC call still open? If yes can forward that to SAP? Many thanks for your effort.

**Comment by jrodriguez-rc** [comment]
The issue reported to SAP was closed by inactivity, I was waiting for this patch to test and report feedback.

**Comment by mkaesemann** [comment]
Small update: Staginging issue/filtering issue is still there in 7.70 PL5 as well.

**Comment by mbtools** [comment]
Further [delays](https://launchpad.support.sap.com/#/notes/2901278): Looks like Sept 2022 + 3 months.

**Comment by christianguenter2** [comment]
SAP Note [2901278](https://launchpad.support.sap.com/#/notes/2901278) was updated regarding `SAPEVENT` and new note [3228419](https://launchpad.support.sap.com/#/notes/3228419) was created. 

![grafik](https://user-images.githubusercontent.com/17437789/180942943-9c3cad9c-5fd1-4468-9162-580bce2ef0f7.png)

Though not yet released.
![grafik](https://user-images.githubusercontent.com/17437789/180942874-1f4475f8-8c11-4853-885b-1a36866b3ebc.png)

**Comment by mbtools** [comment]
More delays:

![image](https://user-images.githubusercontent.com/59966492/198052788-95e7d76c-a713-4701-b734-2697878ae97b.png)

**Comment by gregorwolf** [comment]
I've just updated Edge to:

Version 109.0.1518.55 (Official build) (64-bit)

and I can confirm that this issue still does exist. Will watch SAP Note [3228419](https://launchpad.support.sap.com/#/notes/3228419) now.

**Comment by christianguenter2** [comment]
Good news I guess
[3331099 - SAP GUI for Windows Edge HTML control: Custom URI scheme support is now available](https://me.sap.com/notes/3331099/E)

**Comment by christianguenter2** [comment]
Note was updated
![grafik](https://github.com/abapGit/abapGit/assets/17437789/5133a672-c6a0-4d34-8efc-500ff86af325)

**Comment by WegnerDan** [comment]
SAP GUI 800 PL03 seems to break actions in abapgit:

https://github.com/abapGit/abapGit/assets/6908247/5d9c78dc-75ff-4b14-a509-e6aa65899c9f

Probably related to notes 3331099, 3335007, 3334529

![firefox_2Zy8IXBWM7](https://github.com/abapGit/abapGit/assets/6908247/cc6ecc02-604e-462a-8e8a-b176cb63a560)

**Comment by mbtools** [comment]
I think I see the issue: The actions are in upper case but AG expects them lower case. @WegnerDan can you test the following fix, please?

https://github.com/abapGit/abapGit/blob/main/src/ui/core/zcl_abapgit_gui_event.clas.abap#L47

```abap
    zif_abapgit_gui_event~mv_action       = to_lower( iv_action ).
```

**Comment by WegnerDan** [comment]
Yep, this works!

**Comment by WegnerDan** [comment]
Yep, "Patch" and "Staging" also works

**Comment by mbtools** [comment]
Excellent. Thanks!

**Comment by ubabap** [comment]
What is the solution for this issue?   i found only note 331099 here. his note is not relevant on my system. Still have SAPGUI 770  patchlevel 5 
is it fixed in https://github.com/abapGit/abapGit/pull/6336 ?   and also gui patch needed?
Using the last ABAPgit Standalone and SAPGUI 770  patchlevel 5   i still have this issue

**Comment by mbtools** [comment]
#6339 is still open and tracking the overall status. We will need to adjust AG to handle the uppercase SAPEVENT and wait for the next SAP GUI patch that fixes encoding of URL parameters including slashes.
